name: Code Quality & Lint

on:
  push:
    branches: [ master, 'release/**' ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3

      - name: Run Kotlin Linting (detekt)
        run: ./gradlew detekt --no-daemon --stacktrace --continue || echo "Detekt completed with warnings"

      - name: Run Kotlin Code Style (ktlint)
        run: ./gradlew ktlintCheck --no-daemon --stacktrace --continue || echo "Ktlint completed with warnings"


      - name: Upload detekt reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detekt-reports
          path: |
            build/reports/detekt/
            build/reports/ktlint/
          if-no-files-found: ignore