name: Regenerate Types (generator)

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 2 * * 0'   # Mingguan, sesuaikan
  workflow_dispatch:
  push:
    paths:
      - 'generator/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: generator/package-lock.json

      - name: Install generator deps
        working-directory: ./generator
        run: |
          npm ci

      - name: Run generator
        working-directory: ./generator
        run: |
          npm run generate

      - name: Commit generated changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(generator): regenerate types and client"
          file_pattern: |
            packages/types/**
            packages/client/**
          branch: regen/codegen-${{ github.run_id }}
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions@github.com

      - name: Configure git to use PAT for pushes (if provided)
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          if [ -n "$PAT" ]; then
            echo "Configuring git to use PAT for pushes"
            git config --global url."https://$PAT@github.com/".insteadOf "https://github.com/"
          else
            echo "No PERSONAL_ACCESS_TOKEN set; skipping git config"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: "chore(generator): regenerate types and client"
          branch: regen/codegen-${{ github.run_id }}
          title: "Regenerate types & client (automated)"
          body: "Automated regeneration of types and client from OpenAPI spec."
