name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3

      - name: Run all tests
        run: ./gradlew :packages:client:jvmTest --no-daemon --stacktrace --continue

      - name: Build release artifacts
        run: ./gradlew :packages:client:build --no-daemon --stacktrace --continue

      - name: Generate changelog
        id: changelog
        run: |
          # Extract version from tag or input
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Generate basic changelog
          echo "## Changes in v$VERSION" > changelog.md
          echo "" >> changelog.md
          echo "### 🚀 Features" >> changelog.md
          echo "- Production-ready NEAR JSON-RPC Kotlin client" >> changelog.md
          echo "- Real NEAR network connectivity verified" >> changelog.md
          echo "- Android-compatible JVM target" >> changelog.md
          echo "" >> changelog.md
          echo "### 🛠 Technical" >> changelog.md
          echo "- JsonRpcTransport with JSON-RPC 2.0 support" >> changelog.md
          echo "- Comprehensive unit and integration tests" >> changelog.md
          echo "- Auto-generated types from NEAR OpenAPI spec" >> changelog.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          release_name: Release v${{ steps.changelog.outputs.version }}
          body_path: changelog.md
          draft: false
          prerelease: false

      - name: Publish to GitHub Packages
        run: |
          ./gradlew :packages:client:publishToMavenLocal
          # Note: For publishing to GitHub Packages, you would need:
          # ./gradlew :packages:client:publish
          # With proper repository configuration in build.gradle.kts

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: near-jsonrpc-client-${{ steps.changelog.outputs.version }}
          path: |
            packages/client/build/libs/*.jar
            packages/types/build/libs/*.jar
          if-no-files-found: ignore